name: Notify Slack Channel on Pull Request Updates
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Send Slack notification
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        run: |
          echo "Sending Slack notification..."
          node .github/workflows/notify.js