name: Notify Slack Channel on Pull Request Updates
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install
      - name: Send Slack notification
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        run: |
          echo "Sending Slack notification..."
          node .github/workflows/notify.js