name: Notify Slack Channel on Pull Request Updates
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install @slack/web-api && npm install @actions/github
      - name: Send Slack notification
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        run: |
          echo "Sending Slack notification..."
          node .github/workflows/notify.js