name: Test Workflow 2

on:
  workflow_dispatch: # Permite disparar o workflow manualmente

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Test Message
        run: echo "Test message"